name: ifuckingloveamsterdam
favicon: null
layout_spectrum: 0.7531
typography_spectrum: 0.21557
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#221F20'
    - '#8F8D8D'
    - '#CFCFCF'
    - '#747373'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.8646616
purpose: []
